### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by friktiny** [sujalgoel/Status-Checker#2]
when i do !setup channel it showing error 
![image](https://user-images.githubusercontent.com/76273378/131170607-e5604932-58a7-47e1-be88-b887d333a897.png)
![image](https://user-images.githubusercontent.com/76273378/131170638-1afe8fcf-312d-4b09-8a1c-6393363bc4cc.png)

**Comment by sujalgoel** [comment]
which discordjs version?

**Comment by friktiny** [comment]
> which discordjs version?

![image](https://user-images.githubusercontent.com/76273378/131171262-b884f4d3-4584-476d-afaf-5cfa1e5eb5c7.png)
12.5.1

**Comment by sujalgoel** [comment]
did you modify something?

**Comment by friktiny** [comment]
> did you modify something?

no

**Comment by friktiny** [comment]
can you help me?

**Comment by sujalgoel** [comment]
It was working fine for me but still, I have updated DJS version to 12.5.3 and It is still working for me.

**Comment by friktiny** [comment]
let me test
